# Run tests and lint inside node containers
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18-alpine, 20-alpine, 22-alpine]

    container:
      image: node:${{ matrix.node-version }}

    steps:
    - uses: actions/checkout@v4
    - run: apk add --no-cache make
    - run: make install
    - run: make test
    - run: make lint
